export const SCHEMA = 2;
export const MEALS = {breakfast:'Завтрак',lunch:'Обед',dinner:'Ужин'};
export const CATEGORIES = {breakfast:'Завтраки',lunch:'Обеды',dinner:'Ужины',dessert:'Десерты'};
export const GROUPS = ['Овощи и зелень','Фрукты и ягоды','Молочные продукты','Мясо и птица','Рыба','Крупы и макароны','Бакалея','Прочее'];
export const uid=()=>globalThis.crypto?.randomUUID?.() || 'id-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2);
export function dateKey(d=new Date()){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
export function addDays(key,n){const d=new Date(key+'T12:00:00');d.setDate(d.getDate()+n);return dateKey(d);}
export function monday(key){const d=new Date(key+'T12:00:00');return addDays(key,-((d.getDay()+6)%7));}
export function fresh(){return {schemaVersion:SCHEMA,settings:{familySize:2},favorites:[],jobs:[],plan:[],batches:[],pantry:{},manual:[],updatedAt:new Date().toISOString()};}
export function amount(n){return Number((Number(n)||0).toFixed(2));}
export function ingredientKey(i){return i.id+'|'+i.unit;}
export function scaledIngredients(recipe,portions){return recipe.ingredients.map(i=>({...i,quantity:i.quantity===null?null:amount(i.quantity*portions/recipe.servings)}));}
export function requirements(state,recipes){const map=new Map();for(const j of state.jobs.filter(j=>!j.cookedBatchId&&state.plan.some(e=>e.jobId===j.id&&!e.eatenAt))){const r=recipes.get(j.recipeId);if(!r)continue;for(const i of scaledIngredients(r,j.portions).filter(i=>i.id!=='water')){const k=ingredientKey(i);const row=map.get(k)||{...i,key:k,quantity:0,recipeIds:[]};row.quantity=i.quantity===null?null:amount((row.quantity||0)+i.quantity);row.recipeIds.push(r.id);map.set(k,row);}}return [...map.values()];}
export function shopping(state,recipes){return requirements(state,recipes).map(i=>{const stock=state.pantry[i.key];const have=stock?.quantity||0;const covered=i.quantity===null?!!stock:have>=i.quantity;return {...i,needed:i.quantity===null?null:Math.max(0,amount(i.quantity-have)),covered,stock:have,status:covered?(stock?.origin==='bought'?'bought':'home'):'buy'};}).concat(state.manual.map(m=>({...m,key:'manual|'+m.id,manual:true,needed:m.quantity,covered:!!m.checked,status:m.checked?'bought':'buy',recipeIds:[]})));}
export function missingCount(r,state){return scaledIngredients(r,r.servings).filter(i=>i.id!=='water').filter(i=>{const s=state.pantry[ingredientKey(i)];return !s||(i.quantity!==null&&s.quantity<i.quantity);}).length;}
export function markStock(state,key,quantity,origin='home'){if(quantity===0){delete state.pantry[key];return;}state.pantry[key]={quantity:quantity===null?1:amount(quantity),origin,updatedAt:new Date().toISOString()};}
export function newPlan(state,recipe,{date,meal,portions,days,batchId=null,replaceId=null}){if(!MEALS[meal]||!validDate(date)||!finiteRange(portions,.25,100)||!Number.isInteger(days)||days<1||days>14)throw Error('Проверьте дату, порции и дни.');let batch=batchId?state.batches.find(b=>b.id===batchId):null;if(batchId&&!batch)throw Error('Заготовка не найдена.');if(batch){if(batch.recipeId!==recipe.id)throw Error('Заготовка относится к другому блюду.');const reserved=state.plan.filter(p=>p.batchId===batch.id&&!p.eatenAt&&p.id!==replaceId).reduce((n,p)=>n+p.portions,0);if(portions+reserved>batch.remaining+.001)throw Error(`Свободно ${amount(batch.remaining-reserved)} порций. Уменьшите порции или приготовьте новую партию.`);}if(replaceId)removeEntry(state,replaceId);const job=batch?null:{id:uid(),recipeId:recipe.id,portions,days,startDate:date,meal,createdAt:new Date().toISOString()};if(job)state.jobs.push(job);for(let i=0;i<days;i++){state.plan.push({id:uid(),date:addDays(date,i),meal,recipeId:recipe.id,jobId:job?.id||null,batchId:batch?.id||null,portions:(Math.floor(Math.round(portions*100)/days)+(i<Math.round(portions*100)%days?1:0))/100,eatenAt:null});}return job;}
export function removeEntry(state,id){const entry=state.plan.find(e=>e.id===id);if(!entry)return;state.plan=state.plan.filter(e=>e.id!==id);const job=state.jobs.find(j=>j.id===entry.jobId);if(job&&!job.cookedBatchId){const es=state.plan.filter(e=>e.jobId===job.id);if(!es.length)state.jobs=state.jobs.filter(j=>j.id!==job.id);else{job.portions=amount(es.reduce((s,e)=>s+e.portions,0));job.days=es.length;job.startDate=es.map(e=>e.date).sort()[0];}}}
export function removeJob(state,id){for(const e of [...state.plan].filter(e=>e.jobId===id))removeEntry(state,e.id);}
export function cook(state,recipe,{portions,actualPortions=portions,days,date=dateKey(),jobId=null}){if(!finiteRange(portions,.25,100)||!finiteRange(actualPortions,.25,100)||!Number.isInteger(days)||days<1||days>14||!validDate(date))throw Error('Проверьте количество порций, дни и дату.');const job=jobId?state.jobs.find(j=>j.id===jobId):null;if(jobId&&(!job||job.cookedBatchId||job.recipeId!==recipe.id))throw Error('Эта партия уже приготовлена или план изменился.');const reserved=job?state.plan.filter(e=>e.jobId===job.id&&!e.eatenAt).reduce((n,e)=>n+e.portions,0):0;const batch={id:uid(),recipeId:recipe.id,cookedAt:date,initial:actualPortions,remaining:actualPortions,endDate:addDays(date,days-1),expectedDays:days,jobId:job?.id||null};state.batches.push(batch);if(job){job.cookedBatchId=batch.id;state.plan.filter(e=>e.jobId===job.id).forEach(e=>e.batchId=batch.id);}
for(const i of scaledIngredients(recipe,portions)){const k=ingredientKey(i),s=state.pantry[k];if(s&&i.quantity!==null){s.quantity=amount(Math.max(0,s.quantity-i.quantity));if(s.quantity===0)delete state.pantry[k];}}
return {batch,shortage:Math.max(0,amount(reserved-actualPortions))};}
export function eat(state,id){const e=state.plan.find(p=>p.id===id);if(!e)throw Error('Приём пищи не найден.');const b=state.batches.find(b=>b.id===e.batchId);if(!b)throw Error('Сначала приготовьте блюдо.');if(e.eatenAt){b.remaining=amount(b.remaining+e.portions);b.initial=Math.max(b.initial,b.remaining);e.eatenAt=null;return;}if(b.remaining+.001<e.portions)throw Error(`В заготовке осталось ${b.remaining} порций, нужно ${e.portions}. Приготовьте новую партию или измените этот приём пищи.`);b.remaining=amount(Math.max(0,b.remaining-e.portions));e.eatenAt=new Date().toISOString();}
// Explicit, idempotent confirmation: a double tap must never undo a meal.
export function consume(state,id,quantity){
 const e=state.plan.find(p=>p.id===id);if(!e)throw Error('Приём пищи не найден.');
 if(e.eatenAt)return false;
 if(!finiteRange(quantity,.01,100))throw Error('Укажите количество съеденных порций.');
 if(amount(quantity)!==e.portions)moveEntry(state,id,{date:e.date,meal:e.meal,portions:quantity});
 eat(state,id);return true;
}
export function todayOverview(state,recipes,date=dateKey()){
 const entries=state.plan.filter(e=>e.date===date).sort((a,b)=>Object.keys(MEALS).indexOf(a.meal)-Object.keys(MEALS).indexOf(b.meal));
 const pending=entries.filter(e=>!e.eatenAt&&!e.batchId),jobIds=new Set(pending.map(e=>e.jobId));
 const available=new Map(state.batches.map(b=>[b.id,b.remaining])),ready=[],shortage=[];
 for(const e of entries.filter(e=>!e.eatenAt&&e.batchId)){
  const left=available.get(e.batchId)||0;
  if(left+.001>=e.portions){ready.push(e);available.set(e.batchId,amount(left-e.portions));}else shortage.push(e);
 }
 const todayState={...state,jobs:state.jobs.filter(j=>jobIds.has(j.id)),manual:[]};
 const shoppingAll=shopping(todayState,recipes);
 return {entries,pending,ready,shortage,jobIds,shoppingAll,shopping:shoppingAll.filter(i=>!i.covered),missingMeals:Object.keys(MEALS).filter(meal=>!entries.some(e=>e.meal===meal)),completed:entries.filter(e=>e.eatenAt)};
}
export function batchRemaining(state,id,value){if(!finiteRange(value,0,100))throw Error('Остаток должен быть от 0 до 100.');const b=state.batches.find(b=>b.id===id);if(!b)throw Error('Заготовка не найдена.');b.remaining=amount(value);b.initial=Math.max(b.initial,b.remaining);}
export function rebindEntry(state,id,batchId){const e=state.plan.find(p=>p.id===id),b=state.batches.find(b=>b.id===batchId);if(!e||!b||e.eatenAt||e.recipeId!==b.recipeId)throw Error('Нельзя связать этот приём пищи с заготовкой.');const reserved=state.plan.filter(p=>p.id!==id&&p.batchId===b.id&&!p.eatenAt).reduce((n,p)=>n+p.portions,0);if(reserved+e.portions>b.remaining+.001)throw Error('В этой заготовке недостаточно свободных порций.');const oldId=e.jobId; e.jobId=null;e.batchId=b.id;const job=state.jobs.find(j=>j.id===oldId);if(job&&!job.cookedBatchId){const es=state.plan.filter(p=>p.jobId===oldId);if(es.length){job.portions=amount(es.reduce((n,p)=>n+p.portions,0));job.days=es.length;job.startDate=es.map(p=>p.date).sort()[0];}else state.jobs=state.jobs.filter(j=>j.id!==oldId);}}
export function moveEntry(state,id,{date,meal,portions}){const e=state.plan.find(e=>e.id===id);if(!e||e.eatenAt||!validDate(date)||!MEALS[meal]||!finiteRange(portions,.01,100))throw Error('Проверьте дату, приём пищи и порции.');const b=state.batches.find(b=>b.id===e.batchId);if(b){const other=state.plan.filter(p=>p.batchId===b.id&&!p.eatenAt&&p.id!==id).reduce((n,p)=>n+p.portions,0);if(other+portions>b.remaining+.001)throw Error('В заготовке недостаточно свободных порций.');}const j=state.jobs.find(j=>j.id===e.jobId);if(j&&!j.cookedBatchId){const other=state.plan.filter(p=>p.jobId===j.id&&p.id!==id).reduce((n,p)=>n+p.portions,0);if(other+portions>100)throw Error('В одной партии может быть до 100 порций. Добавьте отдельное приготовление.');j.portions=amount(other+portions);j.startDate=[date,...state.plan.filter(p=>p.jobId===j.id&&p.id!==id).map(p=>p.date)].sort()[0];}Object.assign(e,{date,meal,portions:amount(portions)});}
const validDate=s=>typeof s==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(s)&&dateKey(new Date(s+'T12:00:00'))===s;
const finiteRange=(n,min,max)=>typeof n==='number'&&Number.isFinite(n)&&n>=min&&n<=max;
export function validateImport(input,recipes){if(!input||typeof input!=='object')throw Error('Это не файл Portionly.');const s=input.data||input;if(![1,2].includes(s.schemaVersion))throw Error('Эта версия резервной копии не поддерживается.');for(const key of ['favorites','jobs','plan','batches','manual'])if(!Array.isArray(s[key]))throw Error('В резервной копии нет '+key);if(s.plan.length>20000||s.jobs.length>10000||s.batches.length>10000||s.manual.length>1000)throw Error('Слишком большая резервная копия.');if(!s.settings||!finiteRange(s.settings.familySize,1,12)||!Number.isInteger(s.settings.familySize))throw Error('Неверный размер семьи.');if(!s.pantry||typeof s.pantry!=='object'||Array.isArray(s.pantry))throw Error('Неверный запас продуктов.');const copy=JSON.parse(JSON.stringify(s));copy.schemaVersion=SCHEMA;const ids=new Set();for(const j of copy.jobs){if(typeof j.id!=='string'||ids.has(j.id)||!recipes.has(j.recipeId)||!validDate(j.startDate)||!MEALS[j.meal]||!finiteRange(j.portions,.01,100)||!Number.isInteger(j.days)||j.days<1||j.days>14)throw Error('Повреждён план приготовления.');ids.add(j.id);}const bids=new Set();for(const b of copy.batches){if(typeof b.id!=='string'||bids.has(b.id)||!recipes.has(b.recipeId)||!validDate(b.cookedAt)||!validDate(b.endDate)||!finiteRange(b.initial,.01,100)||!finiteRange(b.remaining,0,100)||b.remaining>b.initial)throw Error('Повреждены заготовки.');if(b.jobId&&!ids.has(b.jobId))throw Error('Нарушена связь заготовки с планом.');bids.add(b.id);}for(const j of copy.jobs)if(j.cookedBatchId&&!bids.has(j.cookedBatchId))throw Error('Не найдена приготовленная партия.');const eids=new Set();for(const e of copy.plan){if(typeof e.id!=='string'||eids.has(e.id)||!recipes.has(e.recipeId)||!validDate(e.date)||!MEALS[e.meal]||!finiteRange(e.portions,.01,100)||e.jobId&&!ids.has(e.jobId)||e.batchId&&!bids.has(e.batchId)||e.eatenAt&&(!e.batchId||typeof e.eatenAt!=='string'||!Number.isFinite(Date.parse(e.eatenAt))))throw Error('Повреждён недельный план.');if(e.jobId&&copy.jobs.find(j=>j.id===e.jobId).recipeId!==e.recipeId||e.batchId&&copy.batches.find(b=>b.id===e.batchId).recipeId!==e.recipeId)throw Error('Блюдо и партия не совпадают.');eids.add(e.id);}if(copy.favorites.some(id=>!recipes.has(id)))throw Error('В избранном есть неизвестное блюдо.');const allowed=new Set([...recipes.values()].flatMap(r=>r.ingredients.map(ingredientKey)));for(const [k,v]of Object.entries(copy.pantry)){if(!allowed.has(k)||!v||!finiteRange(v.quantity,0,1000000)||!['home','bought'].includes(v.origin))throw Error('Повреждён запас продуктов.');}for(const m of copy.manual){if(typeof m.id!=='string'||typeof m.name!=='string'||m.name.length>120||!m.name.trim()||!GROUPS.includes(m.group)||!finiteRange(m.quantity,0,1000000)||typeof m.unit!=='string'||m.unit.length>20||typeof m.checked!=='boolean')throw Error('Повреждён список покупок.');}return copy;}
